name: Deploy To S3 And Invalidate Cloudfront

on:
    push:
        branches:
            - main

jobs:
    My-Deploy_Job:
        runs-on: ubuntu-latest
        steps:
            - name: Github Repository 파일 불러오기
              run: actions/checkout@v4
